#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

set -e
source ${PROJECT_ROOT}/.docksal/vars/colors

#-------------------------- Execution --------------------------------

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
# Run reset to destroy all existing volumes/containers to prevent naming
# collisions and other issues.
fin project reset -f

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"
# This runs inside cli using https://docs.docksal.io/fin/custom-commands/#target_cli
# (Notice 'exec_target = cli' at the top of the file that this is calling)
fin init-site #calling .docksal/commands/init-site

echo -e "${green_bg} DONE! ${NC}${green} Completed all initialization steps.${NC}"
echo -e "${green} If you want to know more about these steps, start at .docksal/commands/init${NC}"

#-------------------------- END: Execution --------------------------------
