#!/usr/bin/env bash

## Runs phpcs to display code sniffing violations.

# Abort if anything fails
set -e

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
WEB_CONTAINER_PROJECT_ROOT="/var/www"
PHPCS="${WEB_CONTAINER_PROJECT_ROOT}/vendor/bin/phpcs"
PHPCBF="${WEB_CONTAINER_PROJECT_ROOT}/vendor/bin/phpcbf"

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Yes/no confirmation dialog with an optional message
# @param $1 confirmation message
_confirm ()
{

while true; do
    read -p "$1 [y/n]: " answer
    case "$answer" in
        [Yy]|[Yy][Ee][Ss] )
            break
            ;;
        [Nn]|[Nn][Oo] )
            exit 1
            ;;
        * )
        echo 'Please answer yes or no.'
    esac
done
}

# Exits fin if previous command exited with non-zero code
if_failed ()
{
    if [ ! $? -eq 0 ]; then
        echo-red "$*"
        exit 1
    fi
}

cd $PROJECT_ROOT

# Make sure Composer dependencies are installed
if [[ ! -d "$PROJECT_ROOT/vendor/squizlabs" ]]; then
	fin exec "cd $PROJECT_ROOT && composer install --prefer-source --no-interaction"
fi


if [[ ! -x "$PROJECT_ROOT/vendor/bin/phpcs" ]]; then
    echo -e "${yellow} bin/phpcs AND bin/phpcbf ${NC} are not set to be executable."
    _confirm "Fix automatically?"
    chmod +x "$PROJECT_ROOT/vendor/bin/phpcs"
    chmod +x "$PROJECT_ROOT/vendor/bin/phpcbf"
    if_failed "Could not make $PROJECT_ROOT/vendor/bin/phpcs or $PROJECT_ROOT/vendor/bin/phpcbf executable"
fi

fin exec "$PHPCS --config-set installed_paths $WEB_CONTAINER_PROJECT_ROOT/vendor/drupal/coder/coder_sniffer"
fin exec "$PHPCS --config-set colors 1"
# To export output into a file use --report-file=file.csv
fin exec "$PHPCS --standard=Drupal --extensions='inc,php,module' --exclude=Drupal.NamingConventions.ValidClassName,Drupal.NamingConventions.ValidFunctionName --error-severity=1 --warning-severity=8 web/modules/custom -s"
