#!/usr/bin/env bash

## Quick reminder of useful terminology
##
## Usage: fin remindme

# Set the colors that the console will use for output.
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }


echo -e "${green_bg} Docker ${NC}${green} Software that allows you to setup, run, and manage virtualized containers on your local machine. ${NC}"
echo -e "${green_bg} Container ${NC}${green} A unit of software that packages up code and all its dependencies so the application runs quickly and reliably from one computing environment to another. ${NC}"
echo -e "${green_bg} Image ${NC}${green} A read-only template that contains a set of instructions for creating a container that can run on the Docker platform. ${NC}"
echo -e "${green_bg} Volume ${NC}${green} Where Docker stores the data generated in a container. ${NC}"
echo -e "${green_bg} Docksal ${NC}${green} A set of commands that make Docker easier to managage (anytime you start a command with 'fin' you are using docksal). ${NC}"
echo -e "${green_bg} Docker glossary ${NC}${green} https://docs.docker.com/glossary/ ${NC}"
echo -e "${green_bg} Docksal docs ${NC}${green} https://docs.docksal.io/ ${NC}"

echo -e "${yellow}Feel free to add more reminders here that you might find useful!${NC}"
